/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bastaewan;

import java.awt.*;
import javax.swing.*;
import com.mycompany.bastaewan.LogoUtils;
// removed searchbar imports (no longer needed)

/**
 *
 * @author JDLM
 */
public class MainDashboard extends javax.swing.JFrame {

    // design palette (blue & yellow theme)
    private javax.swing.JButton selectedNav;
    private static final Color PRIMARY = new Color(0, 102, 204); // deep blue
    private static final Color PRIMARY_DARK = new Color(0, 73, 153); // darker blue
    private static final Color ACCENT = new Color(255, 204, 0); // golden yellow
    private static final Color SUCCESS = new Color(39, 174, 96); // keep green for status
    private static final Color WARNING = ACCENT; // reuse yellow
    private static final Color DANGER = new Color(231, 76, 60);
    private static final Color BG_LIGHT = new Color(245, 247, 250);
    private static final Color TEXT_DARK = new Color(30, 30, 60);
    private static final Font HEADER_FONT = new Font("Segoe UI", Font.BOLD, 18);
    private static final Font NAV_FONT = new Font("Segoe UI", Font.BOLD, 13);

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainDashboard.class.getName());

    /**
     * Creates new form MainDashboard
     */
    public MainDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(new java.awt.BorderLayout());
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainContent = new javax.swing.JPanel(new java.awt.CardLayout());
        dashboardPage1 = new com.mycompany.bastaewan.DashboardPage();
        equipmentPage1 = new com.mycompany.bastaewan.EquipmentPage();
        issueReportsPage1 = new com.mycompany.bastaewan.IssueReportsPage();
        maintenancePage2 = new com.mycompany.bastaewan.MaintenancePage();
        repairLogsPage1 = new com.mycompany.bastaewan.RepairLogsPage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TechTrack - Hardware Monitor");
        setSize(1200, 750);
        setLayout(new BorderLayout());

        // top bar
        JPanel topBar = new JPanel(new BorderLayout());
        topBar.setBackground(PRIMARY_DARK);
        topBar.setPreferredSize(new Dimension(0, 50));
        JLabel titleLabel = new JLabel("  TechTrack   |   Hardware Monitor");
        titleLabel.setFont(HEADER_FONT);
        titleLabel.setForeground(Color.WHITE);
        topBar.add(titleLabel, BorderLayout.WEST);
        JPanel userPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 12));
        userPanel.setOpaque(false);
        JLabel userLabel = new JLabel("Welcome, " + SessionManager.getUsername());
        userLabel.setForeground(Color.WHITE);
        userLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        userPanel.add(userLabel);
        JButton logout = new JButton("Logout");
        logout.setFont(new Font("Segoe UI", Font.BOLD, 12));
        logout.setBackground(DANGER);
        logout.setForeground(Color.WHITE);
        logout.setFocusPainted(false);
        logout.setBorderPainted(false);
        logout.setOpaque(true);
        logout.addActionListener(e -> {
            SessionManager.setUser(null, null);
            dispose();
            new LoginFrame().setVisible(true);
        });
        userPanel.add(logout);
        topBar.add(userPanel, BorderLayout.EAST);
        add(topBar, BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(10, 25, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel topBrand = new javax.swing.JPanel();
        topBrand.setBackground(new java.awt.Color(10, 25, 60));
        topBrand.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        // attempt to add logo icon if available (smaller, closer spacing)
        ImageIcon logoIcon = LogoUtils.getLogoIcon(32);
        if (logoIcon != null) {
            JLabel logoLabel = new JLabel(logoIcon);
            logoLabel.setBorder(BorderFactory.createEmptyBorder(2,2,2,6));
            topBrand.add(logoLabel);
        }
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel1.setForeground(new java.awt.Color(220, 230, 250));
        jLabel1.setText("TechTrack");
        topBrand.add(jLabel1);
        jPanel2.add(topBrand, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel nav = new javax.swing.JPanel();
        nav.setBackground(new java.awt.Color(10, 25, 60));
        nav.setLayout(new java.awt.BorderLayout());

        // Navigation buttons with badges
        javax.swing.JPanel navButtons = new javax.swing.JPanel();
        navButtons.setBackground(new java.awt.Color(10, 25, 60));
        navButtons.setLayout(new java.awt.GridLayout(5, 1, 0, 10));
        navButtons.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));

        javax.swing.JButton btnDashboard = createNavButton("Dashboard");
        javax.swing.JButton btnEquipment = createNavButton("Equipment");
        javax.swing.JButton btnIssues = createNavButton("Issue Reports");
        javax.swing.JButton btnRepair = createNavButton("Repair Logs");
        javax.swing.JButton btnMaintenance = createNavButton("Maintenance");

        // default selection style
        selectedNav = btnDashboard;
        btnDashboard.setBackground(ACCENT); // use yellow highlight for selected

        navButtons.add(btnDashboard);
        navButtons.add(btnEquipment);
        navButtons.add(btnIssues);
        navButtons.add(btnRepair);
        navButtons.add(btnMaintenance);

        nav.add(navButtons, java.awt.BorderLayout.NORTH);

        // User profile at bottom
        javax.swing.JPanel userProfile = new javax.swing.JPanel();
        userProfile.setBackground(new java.awt.Color(10, 25, 60));
        userProfile.setLayout(new java.awt.BorderLayout());
        userProfile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(50, 70, 110)));

        javax.swing.JPanel profileContent = new javax.swing.JPanel();
        profileContent.setBackground(new java.awt.Color(10, 25, 60));
        profileContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 10));
        profileContent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        // Avatar circle
        javax.swing.JLabel avatar = new javax.swing.JLabel("JL");
        avatar.setFont(new java.awt.Font("Segoe UI", 1, 16));
        avatar.setForeground(java.awt.Color.WHITE);
        avatar.setOpaque(true);
        avatar.setBackground(ACCENT);
        avatar.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        avatar.setVerticalAlignment(javax.swing.JLabel.CENTER);
        avatar.setPreferredSize(new java.awt.Dimension(44, 44));
        profileContent.add(avatar);

        // Username and role
        javax.swing.JPanel namePanel = new javax.swing.JPanel();
        namePanel.setBackground(new java.awt.Color(10, 25, 60));
        namePanel.setLayout(new java.awt.GridLayout(2, 1, 0, 2));
        javax.swing.JLabel username = new javax.swing.JLabel(SessionManager.getUsername());
        username.setFont(new java.awt.Font("Segoe UI", 1, 12));
        username.setForeground(java.awt.Color.WHITE);
        javax.swing.JLabel role = new javax.swing.JLabel("Admin");
        role.setFont(new java.awt.Font("Segoe UI", 0, 11));
        role.setForeground(new java.awt.Color(150, 160, 180));
        namePanel.add(username);
        namePanel.add(role);
        profileContent.add(namePanel);

        // Online status
        javax.swing.JLabel onlineStatus = new javax.swing.JLabel("●");
        onlineStatus.setFont(new java.awt.Font("Segoe UI", 1, 12));
        onlineStatus.setForeground(SUCCESS);
        profileContent.add(onlineStatus);

        // Profile menu popup
        JPopupMenu profileMenu = new JPopupMenu();
        profileMenu.setBackground(new Color(20, 35, 80));
        profileMenu.setBorder(BorderFactory.createLineBorder(ACCENT, 1));

        JMenuItem viewProfile = new JMenuItem("View Profile");
        viewProfile.setBackground(new Color(20, 35, 80));
        viewProfile.setForeground(Color.WHITE);
        viewProfile.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        viewProfile.addActionListener(e -> JOptionPane.showMessageDialog(this,
                "User: " + SessionManager.getUsername() + "\nRole: Admin\nStatus: Active",
                "User Profile", JOptionPane.INFORMATION_MESSAGE));

        JMenuItem settings = new JMenuItem("Settings");
        settings.setBackground(new Color(20, 35, 80));
        settings.setForeground(Color.WHITE);
        settings.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        settings.addActionListener(e -> JOptionPane.showMessageDialog(this,
                "Settings panel coming soon!", "Settings", JOptionPane.INFORMATION_MESSAGE));

        JMenuItem changePass = new JMenuItem("Change Password");
        changePass.setBackground(new Color(20, 35, 80));
        changePass.setForeground(Color.WHITE);
        changePass.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        changePass.addActionListener(e -> showChangePasswordDialog());

        profileMenu.add(viewProfile);
        profileMenu.addSeparator();
        profileMenu.add(settings);
        profileMenu.add(changePass);

        profileContent.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMenu.show(profileContent, evt.getX(), evt.getY());
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileContent.setBackground(new java.awt.Color(20, 40, 90));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileContent.setBackground(new java.awt.Color(10, 25, 60));
            }
        });

        userProfile.add(profileContent, java.awt.BorderLayout.CENTER);
        nav.add(userProfile, java.awt.BorderLayout.SOUTH);

        jPanel2.add(nav, java.awt.BorderLayout.CENTER);

        // Right content area (card layout)
        mainContent.add(dashboardPage1, "dashboard");
        mainContent.add(equipmentPage1, "equipment");
        mainContent.add(issueReportsPage1, "issues");
        mainContent.add(maintenancePage2, "maintenance");
        mainContent.add(repairLogsPage1, "repairs");

        // default view
        ((java.awt.CardLayout) mainContent.getLayout()).show(mainContent, "dashboard");

        // wire navigation
        btnDashboard.addActionListener(e -> switchCard("dashboard"));
        btnEquipment.addActionListener(e -> switchCard("equipment"));
        btnIssues.addActionListener(e -> switchCard("issues"));
        btnRepair.addActionListener(e -> switchCard("repairs"));
        btnMaintenance.addActionListener(e -> switchCard("maintenance"));

        jPanel1.add(jPanel2, java.awt.BorderLayout.WEST);
        jPanel1.add(mainContent, java.awt.BorderLayout.CENTER);

        // keep NetBeans .form expected name compatible
        MainContent = mainContent;

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        // status bar
        JLabel status = new JLabel("   TechTrack  •  v1.0  •  " +
                new java.text.SimpleDateFormat("MMMM dd, yyyy").format(new java.util.Date()));
        status.setFont(new Font("Segoe UI", Font.PLAIN, 11));
        status.setForeground(new Color(127, 140, 141));
        status.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0,
                new Color(200, 200, 200)));
        status.setPreferredSize(new Dimension(0, 24));
        add(status, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jButton1ActionPerformed

    private void switchCard(String name) {
        java.awt.CardLayout cl = (java.awt.CardLayout) mainContent.getLayout();
        cl.show(mainContent, name);
        // Refresh page data when switching
        if ("dashboard".equals(name)) {
            dashboardPage1.refreshData();
        } else if ("equipment".equals(name)) {
            equipmentPage1.refreshTable();
        } else if ("issues".equals(name)) {
            issueReportsPage1.refreshTable();
        } else if ("repairs".equals(name)) {
            repairLogsPage1.refreshTable();
        } else if ("maintenance".equals(name)) {
            maintenancePage2.refreshTable();
        }
    }

    /**
     * Show a dialog for changing the current user's password.
     */
    private void showChangePasswordDialog() {
        JDialog dlg = new JDialog(this, "Change Password", true);
        dlg.setSize(360, 240);
        dlg.setLocationRelativeTo(this);
        JPanel panel = new JPanel(new GridLayout(4, 2, 8, 8));
        panel.setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        panel.add(new JLabel("Current password:"));
        JPasswordField current = new JPasswordField();
        panel.add(current);
        JCheckBox showCurrent = new JCheckBox("Show");
        showCurrent.setBackground(panel.getBackground());
        panel.add(showCurrent);
        panel.add(new JLabel("New password:"));
        JPasswordField npass = new JPasswordField();
        panel.add(npass);
        JCheckBox showNew = new JCheckBox("Show");
        showNew.setBackground(panel.getBackground());
        panel.add(showNew);
        panel.add(new JLabel("Confirm new password:"));
        JPasswordField cpass = new JPasswordField();
        panel.add(cpass);
        JCheckBox showConfirm = new JCheckBox("Show");
        showConfirm.setBackground(panel.getBackground());
        panel.add(showConfirm);
        // add listeners
        showCurrent.addActionListener(ev -> {
            current.setEchoChar(
                    showCurrent.isSelected() ? (char) 0 : (Character) UIManager.get("PasswordField.echoChar"));
        });
        showNew.addActionListener(ev -> {
            npass.setEchoChar(showNew.isSelected() ? (char) 0 : (Character) UIManager.get("PasswordField.echoChar"));
        });
        showConfirm.addActionListener(ev -> {
            cpass.setEchoChar(
                    showConfirm.isSelected() ? (char) 0 : (Character) UIManager.get("PasswordField.echoChar"));
        });

        JButton ok = new JButton("Change");
        JButton cancel = new JButton("Cancel");
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        btnPanel.add(ok);
        btnPanel.add(cancel);

        dlg.getContentPane().setLayout(new BorderLayout());
        dlg.getContentPane().add(panel, BorderLayout.CENTER);
        dlg.getContentPane().add(btnPanel, BorderLayout.SOUTH);

        ok.addActionListener(e -> {
            String user = SessionManager.getUsername();
            String oldp = new String(current.getPassword());
            String newp = new String(npass.getPassword());
            String conf = new String(cpass.getPassword());
            if (!newp.equals(conf)) {
                JOptionPane.showMessageDialog(dlg, "New password and confirmation do not match.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            boolean changed = SessionManager.changePassword(user, oldp, newp);
            if (changed) {
                JOptionPane.showMessageDialog(dlg, "Password changed successfully.", "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                dlg.dispose();
            } else {
                JOptionPane.showMessageDialog(dlg, "Current password is incorrect.", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        });
        cancel.addActionListener(e -> dlg.dispose());
        dlg.setVisible(true);
    }

    private javax.swing.JButton createNavButton(String text) {
        javax.swing.JButton b = new javax.swing.JButton(text);
        b.setFont(NAV_FONT);
        b.setFocusPainted(false);
        b.setBackground(PRIMARY_DARK);
        b.setForeground(Color.WHITE);
        b.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 20, 12, 20));
        b.setMargin(new Insets(0, 0, 0, 0));
        b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        b.setContentAreaFilled(true);
        b.setOpaque(true);
        b.addActionListener(e -> {
            // deselect previous button
            if (selectedNav != null) {
                selectedNav.setBackground(PRIMARY_DARK);
                selectedNav.setForeground(Color.WHITE);
            }
            // select current button
            b.setBackground(ACCENT);
            b.setForeground(Color.BLACK);
            selectedNav = b;
        });
        return b;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.bastaewan.DashboardPage dashboardPage1;
    private com.mycompany.bastaewan.EquipmentPage equipmentPage1;
    private com.mycompany.bastaewan.IssueReportsPage issueReportsPage1;
    private com.mycompany.bastaewan.MaintenancePage maintenancePage2;
    private com.mycompany.bastaewan.RepairLogsPage repairLogsPage1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel MainContent;
    // End of variables declaration//GEN-END:variables
}
